### ISSUE TITLE
Defer Jquery causes issues

### ISSUE THREAD

**Issue by alexschwantes** [joychetry/infinite-scroll-elementor#2]
So I have this plugin working well now but when trying to optimise the site for performance, there is an issue as I am using some plugins to defer jquery/javascript to improve load performance. Essentially, when jquery is loaded async or deferred, the code errors out as it tries to run before jquery is loaded. 

I manually edited button-load-elementor-ise.php and at line 413 swapped the script for the following which will defer execution of the code until jquery is loaded, and it works like a charm. I saw that there were a few of these invocations in that file and for the infinite-scroll-elementor-ise.php file, so it would probably need to be added to those as well. 

```
<script type="text/javascript">
      function deferInfiniteScroll(method) {
          if (window.jQuery) {
              method();
          } else {
              setTimeout(function() { deferInfiniteScroll(method) }, 50);
          }
      }
      deferInfiniteScroll(function () {
          jQuery(document).ready(function($) {
            $('.elementor-posts').infiniteScroll({
              path: 'a.page-numbers.next',
              append: '.elementor-post',
              history: false ,
              hideNav: 'nav.elementor-pagination',
                status: '.page-load-status',
                        button: '.view-more-button',
                        scrollThreshold: false,
            });
          });
      });
</script>
```

The pro slider for elementor uses this method to load and even goes one step further with their defer method, to check that the intended function `wprs_unslider` has been loaded. Probably also a good idea as you would be unsure if the method is loaded. 
However I don't like the fact they log stuff to the console :(

```
function wprs_defer(method) {
      if (window.jQuery) {
        if(jQuery.fn.wprs_unslider){
          method();
        } else {
          setTimeout(function() { wprs_defer(method) }, 500);
          console.log('waiting for wppro_rev_slider js...');									
        }
      } else {
        setTimeout(function() { wprs_defer(method) }, 100);
        console.log('waiting for jquery..');
      }
    }
```

**Comment by joychetry** [comment]
Thanks for the suggestion @alexschwantes I will look into the matter and release an update in some time. You will receive an update in your Plugins.
Once again, thanks for contributing. 
Good Day 😄

**Comment by joychetry** [comment]
Thanks to your report, I have fixed the issue of Defer Jquery and released a new version.
Kindly update it via the WordPress Plugins page and please report if you find any more issues.
Cheers @alexschwantes

**Comment by alexschwantes** [comment]
@joychetry thanks, it works great!
