### ISSUE TITLE
looses class "elementor-fit-height" after page load.

### ISSUE THREAD

**Issue by markus4000** [joychetry/infinite-scroll-elementor#3]
first page `<div class="elementor-post__thumbnail elementor-fit-height"> `

articles on second page (after loading) `<div class="elementor-post__thumbnail ">`

withoug: elementor-fit-height.

**Comment by joychetry** [comment]
Thanks for reporting @markus4000 .
This will be fixed in the next update.

**Comment by joychetry** [comment]
I have fixed the issue of missing class 'elementor-fit-height' and released a new version.
Kindly update it via the WordPress Plugins page and please report if you find any more issues.
Cheers @markus4000

**Comment by markus4000** [comment]
After the update, my Wordpess crashes:

*Parse error*: syntax error, unexpected ')' in
*/home/httpd/vhosts/site.ch/news.site
<http://site.ch/news.site>*
*.ch/Wordpress/wp-content/plugins/infinite-scroll-elementor-2.2.2/includes/widgets/button-load-elementor-ise.php*
on
line *1041*

Am Sa., 7. Nov. 2020 um 15:52 Uhr schrieb Joy Chetry <
notifications@github.com>:

**Comment by markus4000** [comment]
After the update, my Wordpess crashes: 
Parse error: syntax error, unexpected ')' in /home/httpd/vhosts/site.ch/news.site.ch/Wordpress/wp-content/plugins/infinite-scroll-elementor-2.2.2/includes/widgets/button-load-elementor-ise.php on line 1041

**Comment by joychetry** [comment]
I have checked and fixed the error, kindly update to the newly released v2.3.1.

**Comment by mhr5246** [comment]
https://exirproperties.com/blog/
I still have this problem 

> I have checked and fixed the error, kindly update to the newly released v2.3.1.

**Comment by mhr5246** [comment]
I used this code to solve it
`// Function to add a class to the desired divs
function addFitHeightClass() {
    // Find all divs that have the class 'elementor-post__thumbnail'
    const thumbnails = document.querySelectorAll('div.elementor-post__thumbnail');

    // Check and add the class 'elementor-fit-height'
    thumbnails.forEach(div => {
        if (!div.classList.contains('elementor-fit-height')) {
            div.classList.add('elementor-fit-height');
        }
    });
}

// Initial execution of the function for elements present on page load
document.addEventListener('DOMContentLoaded', function () {
    addFitHeightClass();

    // Define MutationObserver to track changes in the DOM
    const observer = new MutationObserver(function (mutations) {
        mutations.forEach(function (mutation) {
            // If new elements have been added to the DOM
            if (mutation.addedNodes.length > 0) {
                // Check the new elements and add the class
                mutation.addedNodes.forEach(node => {
                    if (node.nodeType === Node.ELEMENT_NODE) {
                        // If the new element is an <a> tag and contains a div.elementor-post__thumbnail inside
                        if (node.querySelector('div.elementor-post__thumbnail')) {
                            addFitHeightClass();
                        }
                    }
                });
            }
        });
    });

    // Observe changes in the part of the DOM where new content is added
    const targetNode = document.body; // Or the element containing the new content
    observer.observe(targetNode, {
        childList: true, // Track the addition or removal of elements
        subtree: true    // Track changes in the entire subtree
    });
});`

**Comment by mhr5246** [comment]
here is a better one 
```
<script>
function addFitHeightClass(target) {
  (target || document).querySelectorAll('div.elementor-post__thumbnail').forEach(div => {
    div.classList.add('elementor-fit-height');
  });
}

document.addEventListener('DOMContentLoaded', () => {
  addFitHeightClass(); // Initial run

  const observer = new MutationObserver(mutations => {
    mutations.forEach(mutation => {
      mutation.addedNodes.forEach(node => {
        if (node.nodeType === Node.ELEMENT_NODE && node.querySelector('div.elementor-post__thumbnail')) {
          addFitHeightClass(node);
        }
      });
    });
  });

  observer.observe(document.body, { childList: true, subtree: true });
});
</script>
```

**Comment by joychetry** [comment]
Thanks for the suggestion @mhr5246 
I will fix it in the new release today.
