### ISSUE TITLE
$(...).infiniteScroll is not a function

### ISSUE THREAD

**Issue by tomslominski** [joychetry/infinite-scroll-elementor#7]
Hi! Thanks for providing this plugin - it does exactly what I need it to, unfortunately only when I'm logged in... :)

When I'm logged out, I get the following error in Firefox 84.0 and Safari 14.0.1 on macOS and iPadOS:

<img width="1313" alt="Screenshot 2021-01-05 at 15 02 46" src="https://user-images.githubusercontent.com/739599/103661837-13f54900-4f67-11eb-83d3-b43a27700427.png">

This happens on a live site I'm working on, as well as on a fresh offline site running on PHP 7.4.1 with WordPress 5.6, Elementor 3.0.15, Elementor Pro 3.0.9 and Infinite Scroll Elementor 2.3.2, and crucially, only when I'm logged out of the site. It works perfectly when I'm logged in as admin. All the relevant scripts seem to be loaded, including the infinite scroll one, so I can't see what the issue is at first glance. Since it's a blank site, I don't think it's an issue with deferred scripts or anything like that, since the live site I tried it on doesn't use that either, and I don't think it's the cache either.

As a sidepoint - why is wp-content/plugins/infinite-scroll-elementor/assets/css/infinite-scroll-elementor.css loaded when it has no useful content?

**Comment by tomslominski** [comment]
It is about order of scripts after all... As a temporary fix, I made infinite-scroll-js depend on jQuery in my child theme:

```
add_action( 'elementor/frontend/after_register_scripts', function() {
	global $wp_scripts;

	if( isset( $wp_scripts->registered['infinite-scroll-js'] ) ) {
		array_push( $wp_scripts->registered['infinite-scroll-js']->deps, 'jquery' );
	}
}, 100 );
```

**Comment by joychetry** [comment]
Hey @tomslominski thanks for reporting the issue, I have not come across the issue that you have initially stated nor had anybody else complained about it. However, I will check and see if I can generate this error.

And as far as the CSS file goes, I will remove it in the next updates.

**Comment by mtahca** [comment]
<img width="702" alt="image" src="https://user-images.githubusercontent.com/13102012/104955301-103bda80-59db-11eb-8f61-6681b1c79e4c.png">
Similar problem only on chrome. No problem with safari on MacOS.
@tomslominski Thanks for tip, its worked.

**Comment by micksp** [comment]
I have the same issue. I'll try out @tomslominski 's approach

**Comment by joychetry** [comment]
Fixed in earlier releases.
